[target.'*']
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse3,+avx,+avx2,+fma"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+sse3,+avx,+avx2,+fma"]

[unstable]
bindeps = true