on: workflow_dispatch
name: Publish to crates.io
jobs:
  build:
    name: Publish to crates.io
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install rust nightly
        run: rustup update nightly-2025-01-05 && rustup default nightly-2025-01-05 && rustup component add rustfmt && rustup component add clippy && rustup component add rust-src && rustup component add llvm-tools
      - name: Build vmimage
        run: cargo run -r --bin build-vmimage
      - name: Package (liblisa)
        run: ./crates.io_version_check.sh liblisa || cargo publish -p liblisa --token ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Package (liblisa-x64-observer-shmqueue)
        run: ./crates.io_version_check.sh liblisa-x64-observer-shmqueue || cargo publish -p liblisa-x64-observer-shmqueue --token ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Package (liblisa-x64-observer)
        run: ./crates.io_version_check.sh liblisa-x64-observer || cargo publish -p liblisa-x64-observer --token ${{ secrets.CRATES_IO_API_TOKEN }} --allow-dirty
      - name: Package (liblisa-enc)
        run: ./crates.io_version_check.sh liblisa-enc || cargo publish -p liblisa-enc --token ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Package (liblisa-synth)
        run: ./crates.io_version_check.sh liblisa-synth || cargo publish -p liblisa-synth --token ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Package (liblisa-semantics-tool)
        run: ./crates.io_version_check.sh liblisa-semantics-tool || cargo publish -p liblisa-semantics-tool --token ${{ secrets.CRATES_IO_API_TOKEN }}